### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/rust-style-guidelines#2]
## Description

A license for this repository/project needs to be added. It can be the `MIT` license.

## Additional Details

There was a case to be made for using the [GNU Free Documentation License](https://www.gnu.org/licenses/#FDL) here since most of the rest of the public `phylum-dev` repos are using GPLv3+. However, further discussion resulted in a decision to use `MIT` instead, with the reason that `FDL` is too strict for the purposes of this documentation.

## Acceptance Criteria

- [x] The license is changed to MIT
- [x] Documentation is updated

**Comment by cd-work** [comment]
Do we want to license this project under GPLv3? I'm not sure how relevant that is for this repository.

**Comment by maxrake** [comment]
> Do we want to license this project under GPLv3? I'm not sure how relevant that is for this repository.

Good point. The [GNU Free Documentation License](https://www.gnu.org/licenses/#FDL) might be more appropriate here. The issue has been updated with this option. Perhaps we need a ruling from @louislang or someone else who might be more familiar with the direction behind these license changes/additions.

**Comment by maxrake** [comment]
Internal discussion resulted in `MIT` as the desired license for this repo. Updating the ticket to say so now...
